# Generated by Django 5.1.1 on 2024-09-20 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('USA', 'United States'), ('IND', 'India')], max_length=100)),
                ('state', models.CharField(choices=[], max_length=100)),
                ('town', models.CharField(choices=[], max_length=100)),
                ('name_of_firm', models.CharField(max_length=255)),
                ('location', models.TextField()),
                ('landmark', models.TextField()),
                ('website_url', models.URLField()),
                ('level', models.CharField(max_length=50)),
                ('type_of_business', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('native_town', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('remarks', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('connected_year', models.IntegerField()),
                ('connected_source', models.CharField(max_length=100)),
                ('working_place', models.CharField(max_length=255)),
                ('native_place', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('scope', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_info_contacts', to='business_info.business')),
            ],
        ),
    ]
