# Generated by Django 5.1.1 on 2024-09-22 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='business',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='business',
            name='email',
        ),
        migrations.RemoveField(
            model_name='business',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='business',
            name='native_town',
        ),
        migrations.RemoveField(
            model_name='business',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='business',
            name='type_of_business',
        ),
        migrations.RemoveField(
            model_name='business',
            name='whatsapp_number',
        ),
        migrations.AddField(
            model_name='business',
            name='type',
            field=models.CharField(default='Default Type', max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('GCB', 'Global Corporate Brand'), ('CB', 'Corporate Brand'), ('RB', 'Regional Brand'), ('LBB', 'Local Big Brand'), ('LB', 'Local Brand'), ('NRI', 'NRI Brand'), ('OT', 'Other')], max_length=3),
        ),
        migrations.AlterField(
            model_name='business',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='landmark',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='level',
            field=models.CharField(choices=[('HO', 'Head Office'), ('BR', 'Branch'), ('SA', 'Stand Alone'), ('OT', 'Other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='town',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=100)),
                ('native_town', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='business_info.business')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
