# Generated by Django 5.1.1 on 2024-09-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_info', '0002_remove_business_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
