# Generated by Django 5.1.1 on 2024-09-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_info', '0003_alter_business_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
