# Generated by Django 5.1.1 on 2024-09-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_info', '0005_remove_contactperson_native_town_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('GCB', 'Global Corporate Brand'), ('CB', 'Corporate Brand'), ('RB', 'Regional Brand'), ('LBB', 'Local Big Brand'), ('LB', 'Local Brand'), ('NRI', 'NRI Brand'), ('OT', 'Other')], max_length=3),
        ),
        migrations.AlterField(
            model_name='business',
            name='level',
            field=models.CharField(choices=[('HO', 'Head Office'), ('BR', 'Branch'), ('SA', 'Stand Alone'), ('OT', 'Other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='business',
            name='name_of_firm',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.CharField(default='Default Type', max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
