# Generated by Django 5.1.1 on 2024-09-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_info', '0006_alter_business_category_alter_business_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='level',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='name_of_firm',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='website_url',
            field=models.URLField(),
        ),
    ]
