# Generated by Django 5.1.1 on 2024-09-23 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_info', '0008_business_native_town_business_remarks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='native_town',
        ),
        migrations.RemoveField(
            model_name='business',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='business',
            name='whatsapp_number',
        ),
        migrations.AddField(
            model_name='contactperson',
            name='native_town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('GCB', 'Global Corporate Brand'), ('CB', 'Corporate Brand'), ('RB', 'Regional Brand'), ('LBB', 'Local Big Brand'), ('LB', 'Local Brand'), ('NRI', 'NRI Brand'), ('OT', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='level',
            field=models.CharField(choices=[('HO', 'Head Office'), ('BR', 'Branch'), ('SA', 'Stand Alone'), ('OT', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.CharField(choices=[('PROD', 'Production'), ('TRAD', 'Trading'), ('SERV', 'Service'), ('OT', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='business_info.business'),
        ),
    ]
