# Generated by Django 5.1.1 on 2024-10-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_info', '0009_remove_business_native_town_remove_business_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='house_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
