# Generated by Django 5.1.1 on 2024-10-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_info', '0010_business_house_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='house_name',
        ),
        migrations.RemoveField(
            model_name='business',
            name='name_of_firm',
        ),
    ]
