# Generated by Django 5.1.1 on 2024-10-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_info', '0011_remove_business_house_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='house_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='name_of_firm',
            field=models.CharField(default='Firm Name', max_length=100),
            preserve_default=False,
        ),
    ]
