# Generated by Django 5.1.1 on 2024-09-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('connected_year', models.PositiveIntegerField()),
                ('connected_source', models.CharField(max_length=100)),
                ('working_place', models.CharField(max_length=255)),
                ('native_place', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('scope', models.CharField(choices=[('INV', 'Investor'), ('CONS', 'Consultant'), ('FL', 'Freelancer'), ('OT', 'Other')], max_length=4)),
                ('status', models.CharField(choices=[('SUP', 'Supporter'), ('INV', 'Investor'), ('CONS', 'Consultant'), ('FL', 'Freelancer'), ('OT', 'Other')], max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
