# Generated by Django 5.1.1 on 2024-09-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_info', '0002_contactperson_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Family', 'Family'), ('Friend', 'Friend'), ('Business', 'Business'), ('Networking', 'Networking'), ('Other', 'Other')], max_length=20)),
                ('profession', models.CharField(max_length=100)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('connected_year', models.PositiveIntegerField()),
                ('connected_source', models.CharField(choices=[('Education', 'Education'), ('Job', 'Job'), ('Business', 'Business'), ('Networking', 'Networking'), ('Social Media', 'Social Media'), ('Family', 'Family'), ('Other', 'Other')], max_length=20)),
                ('working_place', models.CharField(max_length=100)),
                ('native_place', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('scope', models.CharField(choices=[('Investor', 'Investor'), ('Consultant', 'Consultant'), ('Freelancer', 'Freelancer'), ('Other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('Supporter', 'Supporter'), ('Investor', 'Investor'), ('Consultant', 'Consultant'), ('Freelancer', 'Freelancer'), ('Other', 'Other')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactPerson',
        ),
    ]
