# Generated by Django 5.1.1 on 2024-10-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_info', '0003_contact_delete_contactperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='dob',
            field=models.DateField(),
        ),
    ]
