# Generated by Django 5.1.1 on 2024-10-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_info', '0004_alter_contact_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
    ]
